#!/bin/bash

echo "========================================="
echo "   SUGESTÕES DE DOMÍNIOS GRATUITOS"
echo "========================================="
echo ""
echo "🆓 DOMÍNIOS FREENOM (.tk, .ml, .ga, .cf, .gq):"
echo ""
echo "Opções para verificar em https://www.freenom.com:"
echo ""
echo "  1. carteiravirtual.tk"
echo "  2. carteiravirtual.ml"
echo "  3. carteiravirtual.ga"
echo "  4. minhacarteira.tk"
echo "  5. carteiradigital.tk"
echo "  6. minhacarteiradigital.ml"
echo "  7. meusativos.tk"
echo "  8. gestaoativos.tk"
echo ""
echo "========================================="
echo "   COMO REGISTRAR (PASSO A PASSO)"
echo "========================================="
echo ""
echo "1. Acesse: https://www.freenom.com"
echo "2. Digite o nome desejado (ex: carteiravirtual)"
echo "3. Clique em 'Check Availability'"
echo "4. Escolha a extensão (.tk, .ml, etc)"
echo "5. Clique em 'Get it now!'"
echo "6. Clique em 'Checkout'"
echo "7. Selecione período: '12 Months @ FREE'"
echo "8. Complete o cadastro"
echo "9. Confirme o email"
echo ""
echo "========================================="
echo "   DEPOIS DE REGISTRAR"
echo "========================================="
echo ""
echo "Configure no Firebase seguindo as instruções"
echo "do arquivo CONFIGURACAO-DOMINIO.md"
echo ""
echo "========================================="
echo ""
echo "🎯 MINHA RECOMENDAÇÃO:"
echo ""
echo "Para aprender/testar: Use Freenom (.tk, .ml)"
echo "Para projeto sério: Invista R$ 40/ano em .com.br"
echo ""
echo "⚠️  IMPORTANTE: Domínios .tk/.ml podem ser"
echo "bloqueados por alguns antivírus/provedores"
echo ""
